spring:
  profiles:
    active: prod

#1.使用yml文件有层级的结构 缩进
#2.使用yml文件k v之间使用：连接
#3.在进行赋值时：后边必须加空格
--- #环境分割线
spring:  profiles: prodserver:
  port: 8081
  servlet:
    context-path: /jt
      
#为user属性赋值,可以编辑中文      
user:
  id: 100
  userName: 琦玉
  age: 24